"""initial schema

Revision ID: 888fa508b6d9
Revises: 
Create Date: 2026-08-28 16:04:50.019984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '888fa508b6d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odoo_product_category_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('kilataje', sa.String(), nullable=True),
    sa.Column('palabra_clave', sa.String(), nullable=False),
    sa.Column('categoria_odoo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('pysessid', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('pysessid')
    )
    op.create_index('idx_uid_ip_ua', 'sessions', ['user_id', 'ip_address', 'user_agent'], unique=False)
    op.create_table('transfer_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Processing', 'Completed', name='job_status'), nullable=False),
    sa.Column('result', sa.Enum('Success', 'Failure', name='job_result'), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tries', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_transfer_job_st_res_tries_pat', 'transfer_jobs', ['status', 'result', 'tries', 'pushed_at'], unique=False)
    op.create_table('transfer_job_items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('row_id', sa.String(), nullable=False),
    sa.Column('result', sa.Enum('Pending', 'Success', 'Failure', name='item_result'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['transfer_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_transfer_job_item_jid_res', 'transfer_job_items', ['job_id', 'result'], unique=False)
    op.create_table('transfer_job_errors',
    sa.Column('error_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['transfer_job_items.item_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['transfer_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('error_id')
    )
    op.create_index('idx_transfer_job_errors_jid_oat', 'transfer_job_errors', ['job_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transfer_job_errors_jid_oat', table_name='transfer_job_errors')
    op.drop_table('transfer_job_errors')
    op.drop_index('idx_transfer_job_item_jid_res', table_name='transfer_job_items')
    op.drop_table('transfer_job_items')
    op.drop_index('idx_transfer_job_st_res_tries_pat', table_name='transfer_jobs')
    op.drop_table('transfer_jobs')
    op.drop_index('idx_uid_ip_ua', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('odoo_product_category_map')
    # ### end Alembic commands ###
