from datetime import datetime

from sqlalchemy import DateTime, Float, Integer, SmallInteger, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import RemoteBase


class Branch(RemoteBase):
    __tablename__ = 'app_sucursales'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    idTabla: Mapped[int | None] = mapped_column(Integer)
    siglas: Mapped[str | None] = mapped_column(String)
    clave: Mapped[int | None] = mapped_column(Integer)
    ordenamiento: Mapped[int | None] = mapped_column(Integer)
    ip: Mapped[str | None] = mapped_column(String)
    meraki: Mapped[str | None] = mapped_column(String)
    razonSocial: Mapped[str | None] = mapped_column(String)
    nombreComercial: Mapped[str | None] = mapped_column(String)
    alias: Mapped[str | None] = mapped_column(String)
    rfc: Mapped[str | None] = mapped_column(String)
    direccion: Mapped[str | None] = mapped_column(String)
    ciudad: Mapped[str | None] = mapped_column(String)
    municipio: Mapped[str | None] = mapped_column(String)
    idDistrito: Mapped[int | None] = mapped_column(Integer)
    idCorregimiento: Mapped[int | None] = mapped_column(Integer)
    telefono: Mapped[str | None] = mapped_column(String)
    cp: Mapped[int | None] = mapped_column(Integer)
    region: Mapped[str | None] = mapped_column(String)
    zona: Mapped[str | None] = mapped_column(String)
    provincia: Mapped[str | None] = mapped_column(String)
    latitud: Mapped[str | None] = mapped_column(String)
    longitud: Mapped[str | None] = mapped_column(String)
    horarioEmpenos: Mapped[str | None] = mapped_column(String)
    horarioRetiros: Mapped[str | None] = mapped_column(String)
    horarioWU: Mapped[str | None] = mapped_column(String)
    horarioVentas: Mapped[str | None] = mapped_column(String)
    fluyapp: Mapped[str | None] = mapped_column(String)
    googleMaps: Mapped[str | None] = mapped_column(String)
    activa: Mapped[int | None] = mapped_column(Integer)
    cuenta: Mapped[str | None] = mapped_column(String)
    IDOrigen: Mapped[int | None] = mapped_column(Integer)
    Actualizar: Mapped[int | None] = mapped_column(Integer)
    ElConix_Companie: Mapped[str | None] = mapped_column(String)
    ElConix_CentroCosto: Mapped[str | None] = mapped_column(String)
    rucFiscal: Mapped[str | None] = mapped_column(String)
    dvFiscal: Mapped[str | None] = mapped_column(String)
    grupo: Mapped[int | None] = mapped_column(Integer)
    visible: Mapped[int | None] = mapped_column(Integer)
    migrada: Mapped[datetime | None] = mapped_column(DateTime, default=None)
    estado: Mapped[int | None] = mapped_column(Integer)
    eliminado: Mapped[int | None] = mapped_column(Integer)
    doc_jefe_unidad: Mapped[str | None] = mapped_column(String)
    created_at: Mapped[datetime | None] = mapped_column(DateTime, default=None)
    updated_at: Mapped[datetime | None] = mapped_column(DateTime, default=None)


class CaratRating(RemoteBase):
    __tablename__ = 'app_kilatajes'

    idKilataje: Mapped[int] = mapped_column(Integer, primary_key=True)
    Clave: Mapped[int | None] = mapped_column(Integer, default=None)
    nombreKilataje: Mapped[str | None] = mapped_column(String, default=None)
    idTipoEmpeno: Mapped[int | None] = mapped_column(Integer, default=None)
    IDTablaTipo: Mapped[int | None] = mapped_column(Integer, default=None)
    valorxGramo: Mapped[float | None] = mapped_column(Float, default=None)
    Ordenamiento: Mapped[int | None] = mapped_column(Integer, default=None)
    IDOrigen: Mapped[int | None] = mapped_column(Integer, default=None)
    FechaModificacion: Mapped[datetime | None] = mapped_column(
        DateTime, default=None
    )
    Actualizar: Mapped[int | None] = mapped_column(Integer, default=None)
    estado: Mapped[int | None] = mapped_column(Integer, default=None)
    created_at: Mapped[datetime | None] = mapped_column(DateTime, default=None)
    updated_at: Mapped[datetime | None] = mapped_column(DateTime, default=None)


class InventoryEntry(RemoteBase):
    __tablename__ = 'app_detallesentradainventario'

    id_entrada_inventario: Mapped[int] = mapped_column(Integer, primary_key=True)
    idFake: Mapped[int | None] = mapped_column(Integer)
    idOriginal: Mapped[int | None] = mapped_column(Integer)
    folioExcel: Mapped[int | None] = mapped_column(Integer)
    idEntrada: Mapped[str | None] = mapped_column(String(25))
    codigo: Mapped[str | None] = mapped_column(String(20))
    sku: Mapped[str | None] = mapped_column(String(25))
    proceso: Mapped[str | None] = mapped_column(String(20))
    pestana: Mapped[str | None] = mapped_column(String(20))
    tipoDotacion: Mapped[int | None] = mapped_column(Integer)
    idTablaTipo: Mapped[int | None] = mapped_column(Integer())
    cantidad: Mapped[int | None] = mapped_column(Integer)
    descripcion: Mapped[str | None] = mapped_column(String(255))
    genero: Mapped[str | None] = mapped_column(String(20))
    pesoDotacion: Mapped[float | None] = mapped_column(Float)
    kilates: Mapped[int | None] = mapped_column(Integer)
    idTablaKilates: Mapped[int | None] = mapped_column(Integer())
    precioBase: Mapped[float | None] = mapped_column(Float)
    precioAdicional: Mapped[float | None] = mapped_column(Float)
    precio: Mapped[float | None] = mapped_column(Float)
    precioPiedra: Mapped[float | None] = mapped_column(Float)
    costoBase: Mapped[float | None] = mapped_column(Float)
    costoAdicional: Mapped[float | None] = mapped_column(Float)
    costo: Mapped[float | None] = mapped_column(Float)
    estadoPrenda: Mapped[str | None] = mapped_column(String(50))
    marca: Mapped[str | None] = mapped_column(String(100))
    pollera: Mapped[int | None] = mapped_column(Integer)
    modelo: Mapped[str | None] = mapped_column(String(100))
    serie: Mapped[str | None] = mapped_column(String(50))
    color: Mapped[str | None] = mapped_column(String(50))
    sub_categoria: Mapped[str | None] = mapped_column(String(25))
    tamano: Mapped[str | None] = mapped_column(String(50))
    tipoPrenda: Mapped[int | None] = mapped_column(Integer)
    idTablaTipoPrenda: Mapped[int | None] = mapped_column(Integer())
    observaciones: Mapped[str | None] = mapped_column(String(250))
    depreciacion: Mapped[float | None] = mapped_column(Float)
    meses: Mapped[int | None] = mapped_column(Integer)
    maximo: Mapped[float | None] = mapped_column(Float)
    idEmpeno: Mapped[str | None] = mapped_column(String(25))
    tipoContrato: Mapped[int | None] = mapped_column(Integer)
    sucursalOrigen: Mapped[int | None] = mapped_column(Integer)
    sucursalDestino: Mapped[int | None] = mapped_column(Integer)
    tipoEntrada: Mapped[int | None] = mapped_column(Integer)
    tipoSalida: Mapped[int | None] = mapped_column(Integer)
    precioVitrina: Mapped[float | None] = mapped_column(Float)
    impuesto: Mapped[int | None] = mapped_column(Integer)
    cantidadPiedras: Mapped[float | None] = mapped_column(Float)
    pesoPiedras: Mapped[float | None] = mapped_column(Float)
    cantidadDiamantes: Mapped[int | None] = mapped_column(Integer)
    puntos: Mapped[float | None] = mapped_column(Float)
    prestamoDiamante: Mapped[float | None] = mapped_column(Float)
    idOrigen: Mapped[int | None] = mapped_column(Integer)
    destino: Mapped[int | None] = mapped_column(Integer)
    clasificacion: Mapped[str | None] = mapped_column(String(25))
    idReporte: Mapped[int | None] = mapped_column(Integer)
    fechaModificacion: Mapped[datetime | None] = mapped_column(
        DateTime
    )
    actualizar: Mapped[int | None] = mapped_column(SmallInteger)
    created_at: Mapped[datetime | None] = mapped_column(DateTime)
    updated_at: Mapped[datetime | None] = mapped_column(DateTime)


class PawnType(RemoteBase):
    __tablename__ = 'app_tipoempeno'

    idTipoEmpeno: Mapped[int | None] = mapped_column(Integer, primary_key=True)
    nombreTipoEmpeno: Mapped[str | None] = mapped_column(String)
    kilataje: Mapped[int | None] = mapped_column(Integer)
    pesoTipo: Mapped[int | None] = mapped_column(Integer)
    ordenamiento: Mapped[int | None] = mapped_column(Integer)
    vencimiento: Mapped[int | None] = mapped_column(Integer)
    IDOrigen: Mapped[int | None] = mapped_column(Integer)
    fecha: Mapped[datetime | None] = mapped_column(DateTime)
    actualizar: Mapped[int | None] = mapped_column(Integer)
    estado: Mapped[int | None] = mapped_column(Integer)
    created_at: Mapped[datetime | None] = mapped_column(DateTime)
    updated_at: Mapped[datetime | None] = mapped_column(DateTime)
